version: '3.8'

services:
  orquidea-db:
    image: postgres:16-alpine
    container_name: orquidea-postgres-db
    restart: always
    environment:
      POSTGRES_DB: orquidea_db
      POSTGRES_USER: orquidea_user
      POSTGRES_PASSWORD: orquidea_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_orquidea_data:/var/lib/postgresql/data
    networks:
      - orquidea-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orquidea_user -d orquidea_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  orquidea-api:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: orquidea-springboot-api
    restart: always
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
    environment:
      - SERVER_PORT=8080
      - DB_URL=jdbc:postgresql://orquidea-db:5432/orquidea_db
      - DB_USERNAME=orquidea_user
      - DB_PASSWORD=orquidea_pass
      - DB_DDL_AUTO=update
      - DB_SHOW_SQL=true
      - DB_FORMAT_SQL=true
    depends_on:
      orquidea-db:
        condition: service_healthy
    networks:
      - orquidea-network

volumes:
  postgres_orquidea_data:

networks:
  orquidea-network:
    driver: bridge
